---
- name: Install the namenode package
  apt: name={{ item }} state=installed
  with_items: 
   - hadoop-hdfs-namenode

- name: Copy the hadoop configuration files
  template: src=roles/common/templates/hadoop_conf/{{ item }}.j2 dest=/etc/hadoop/conf/{{ item }}
  with_items: 
   - core-site.xml
   - hdfs-site.xml
   - slaves
  notify: restart hadoop master services

- name: Create the data directory for the namenode metadata
  file: path={{ item }} owner=hdfs group=hdfs state=directory
  with_items: hadoop.dfs_namenode_name_dir

- name: Format the namenode
  shell: creates=/usr/lib/hadoop/namenode.formatted su - hdfs -c "hadoop namenode -format" && touch /usr/lib/hadoop/namenode.formatted

- name: Start hadoop namenode services
  service: name=hadoop-hdfs-namenode state=started

- name: Give permissions for mapred users
  shell: creates=/usr/lib/hadoop/namenode.initialized su - hdfs -c "hadoop fs -chown hdfs:hadoop /"; su - hdfs -c "hadoop fs -chmod 0775 /" && touch /usr/lib/hadoop/namenode.initialized

