---
- name: install some tools for convenience
  apt: name={{ item }} state=installed
  with_items:
    - vim
    - tmux
    - git
    - htop
    - nmon
    - build-essential

- name: populate /etc/hosts
  template: src=etc/hosts.j2 dest=/etc/hosts

