---
- name: put fetched SSH key to all other hosts
  copy: src=sshkeys/{{ item }} dest={{ clusteruser_home }}/.ssh/{{ item }}
  with_items:
    - id_rsa
    - id_rsa.pub
    - authorized_keys

- name: cleanup sshkeys
  local_action: command rm -rf sshkeys
  
