---
- name: Download Spark pre-built package
  get_url: url={{ spark['spark_download_url'] }} dest="/tmp/spark-{{ spark['spark_version'] }}.tgz"

- name: Extract Spark archive
  unarchive: copy=no src="/tmp/spark-{{ spark['spark_version'] }}.tgz" dest=/opt/

- name: Create link to Spark directory
  file: src=/opt/spark-{{ spark['spark_version'] }} dest=/opt/spark state=link
