---
- name: apply common configuration to all nodes
  hosts: all
  roles:
    - common

- name: create {{ clusteruser }} user
  hosts: all
  roles:
    - clusteruser_common

- name: fetch SSH key file from master
  hosts: master
  roles: 
    - sshkey_donor 

- name: put fetched SSH key to all other hosts
  hosts: workers
  roles:
    - sshkey_acceptor

#- name: setup nfs master
#  hosts: master
#  roles: 
#    - nfs_server
#
#- name: setup nfs clients
#  hosts: workers
#  roles: 
#    - nfs_client
#
#- name: setup mpi cluster
#  hosts: all
#  roles:
#    - openmpi

- name: install Java
  hosts: all
  roles:
    - java

- name: install Scala
  hosts: all
  roles:
    - scala

- name: prepare for Hadoop installation
  hosts: all
  roles:
    - hadoop_common

- name: setup HDFS namenode
  hosts: master
  roles:
    - hdfs_namenode

- name: setup HDFS datanodes
  hosts: workers
  roles:
    - hdfs_datanode

# TODO deploy standalone Hadoop MR

- name: deploy standalone Spark
  hosts: all
  roles:
    - spark_common

- name: configure Spark master
  hosts: master
  roles:
    - spark_master

# Mesos requires passwordless SSH for user root
- name: setup passwordless SSH for user root - donor key
  hosts: master
  roles:
    - { role: sshkey_donor, clusteruser: root, clusteruser_home: '/root' }

- name: setup passwordless SSH for user root - accept key
  hosts: workers
  roles:
    - { role: sshkey_acceptor, clusteruser: root, clusteruser_home: '/root' }

- name: install Mesos
  hosts: all
  roles:
    - mesos

- name: start Mesos cluster
  hosts: master
  roles: 
    - mesos_master

- name: deploy Spark on Mesos
  hosts: master
  roles:
    - spark_mesos

# TODO deploy Hadoop MR1 on Mesos
