---
# configure NFS clients
# stolen from https://github.com/gc3-uzh-ch/ansible-playbooks/blob/master/roles/common/tasks/nfs-clients.yml

- name: install nfs client
  apt: name=nfs-common state=installed

#- name: Ensure portmap is running 
#  action: service name=portmap state=started enabled=yes

- name: Ensure {{nfsmount}} directory exists
  action: file path={{nfsmount}} state=directory

#- debug: var=hostvars

- name: configure /etc/fstab on clients
  mount: name={{nfsmount}} src={{nfsserver}}:{{nfspath}} fstype=nfs opts={{nfsopts}} state=present

- name: actually mount NFS on clients
  mount: name={{nfsmount}} src={{nfsserver}}:{{nfspath}} fstype=nfs opts={{nfsopts}} state=mounted
